spring.application.name=jwtAuth

spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckpXVFRlc3QxMjM0NTY3ODkw
jwt.expiration=3600000